### ISSUE TITLE
File browser is empty

### ISSUE THREAD

**Issue by jpkrohling** [jpkrohling/katacoda-scenarios#10]
Some update in the last days broke the rendering of the file browser. Clicking "Refresh Tree" doesn't seem to have an effect.

![image](https://user-images.githubusercontent.com/13387/38801501-47a10acc-416a-11e8-8373-a51ea1dd7bea.png)

It used to show the contents of the cloned git repository. Without that, the user can't open the files required for editing.

@BenHall, is this something you are aware of?

**Comment by BenHall** [comment]
I know we worked on some changes with the Ubuntu environment and file editor to improve the reliability. Let me check if that have been deployed.

**Comment by jpkrohling** [comment]
This seems to still be a problem, even after #12: 

![image](https://user-images.githubusercontent.com/13387/38920373-65b3cb64-42f3-11e8-87b8-4faa003c1214.png)

For the record, I'm on Fedora and tested this on Chrome and Firefox. #12 seems to be applied on the scenario I tested:

```
Your Interactive Bash Terminal.


$
$ git clone https://github.com/jpkrohling/opentracing-tutorial -b Katacoda && docker run -d -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:1.3
Cloning into 'opentracing-tutorial'...
remote: Counting objects: 713, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 713 (delta 39), reused 74 (delta 25), pack-reused 617
Receiving objects: 100% (713/713), 218.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (314/314), done.
Checking connectivity... done.
Unable to find image 'jaegertracing/all-in-one:1.3' locally
1.3: Pulling from jaegertracing/all-in-one
eafe7e781724: Pull complete
5c5612f431e5: Pull complete
e78357b13713: Pull complete
Digest: sha256:8683d887cd0726039699d14210ee62a516d699e6297089ff08b01729e909f051
Status: Downloaded newer image for jaegertracing/all-in-one:1.3
43ef71285fb91641105ff2e6e767df050726b89b0df2bb79d524d5e4795a0fe1
$ ls
opentracing-tutorial
$ pwd
/root
$
```

**Comment by jpkrohling** [comment]
@BenHall commented:
> @jpkrohling We're working on the editor and treeview, we'll send you an update when it's improved.

https://github.com/jpkrohling/katacoda-scenarios/issues/11#issuecomment-382308171
