### ISSUE TITLE
Can't send spans via UDP

### ISSUE THREAD

**Issue by jpkrohling** [jpkrohling/katacoda-scenarios#3]
The original tutorial sends spans via UDP to Jaeger. For some reason, this is not working in the Katacoda environment. Judging from the current OpenTracing scenario with the Hot ROD example, it should be possible to send the traces via UDP.

Our workaround is to set the `JAEGER_ENDPOINT`, which forces the usage of `HttpSender`

**Comment by BenHall** [comment]
The `export` that happens in the `env-init` is only for the current bash execution, not the over session which is why you might not see it applied

**Comment by jpkrohling** [comment]
The `export` is part of the workaround. By default, the Jaeger client sends spans via `UDP` (`UdpSender`), but as I can't seem to get it working, I'm forcing the client to use the `HttpSender`.
